### PR TITLE
Nmap

### PR DESCRIPTION
**Pull request by codings9**

### CODE REVIEW

**Comment by mubix** [comment]
Please don't merge your own things so quickly, doesn't allow for time for anyone to review.

**Comment by mubix** [comment]
Check out: https://github.com/pwnwiki/kaliwiki/blob/master/tools/dnsdict6.md for an example on how to format

**Comment by mubix** [comment]
Well, this would be a better link: https://raw2.github.com/pwnwiki/kaliwiki/master/tools/dnsdict6.md

**Comment by codings9** [comment]
Okay thanks got it, that merge button was so tempting, i will just do pull
requests and work of the feedback from the requests, thanks again.

**Pull request merged**
