### PR TITLE
Menu web applications

### PR DESCRIPTION
**Pull request by ThatEidolon**
This should complete the Web Applications menu.

There are a few outstanding issues regarding graphical tools that need to be corrected, but those are tracked under the issue log.

### CODE REVIEW

**Comment by ThatEidolon** [comment]
@WebBreacher Since you are the one who usually reviews these, would you like me to submit smaller pull requests, or wait until a section is complete--like I did with this one?

**Comment by WebBreacher** [comment]
Smaller is easier to process and digest for me. 70+ files to look at
is...daunting and requires many beers/time.

**Comment by ThatEidolon** [comment]
So basically the same process as creating it.

For future menu's I will submit sections as they are completed.

**Comment by WebBreacher** [comment]
Appreciated.

**Comment by ThatEidolon** [comment]
I am closing this pull request, and seeing if I can find a way to chop it
up; it's not as if it will go stale between now and when I figure it out.

**Pull request closed without merging**
