### PR TITLE
Update nmap.md

### PR DESCRIPTION
**Pull request by codings9**
Added "Help Text."

### CODE REVIEW

**Comment by codings9** [comment]
Just inquiring for trivial stuff like just adding the "Help Text" command for nmap-is a pull request still necessary for QA?

**Comment by giga1699** [comment]
Yes, but if nobody replies within 48 hours, go ahead and merge it in.

**Comment by codings9** [comment]
Okay, thanks-i been busy tunning up my cbr for summer and just noticed that
i had an exhaust leak, lost a little hp now we will see how good quicksteel
works, i don't want to buy new headers, lol, soon as my bikes top ends
sweet i will contribute more.

**Comment by giga1699** [comment]
Yeah, no worries.

So all I see is "nmap -h".

Did you mean to commit just that, or the actual help text that comes back?

**Comment by codings9** [comment]
Yes, the help command was missing when i last checked so i added the two
help commands for nmap-thats odd that you only see one command when there
are two methods to evoke help with nmap that i added.

I can also add the output of the actual help text that comes back, but i
did not think this was necessary....but i am down to do anything that helps
and then commit.

**Comment by giga1699** [comment]
Yeah, we've been adding all the outputs so that it's searchable. We'll add specific usage later on.

**Comment by mubix** [comment]
Ya, we should have all the help output available for each command.

**Comment by codings9** [comment]
Okay will do.

**Comment by codings9** [comment]
Okay will do.

**Pull request merged**
